# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_PlainText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_PlainText.setGeometry(QtCore.QRect(120, 90, 521, 91))
        self.txt_PlainText.setObjectName("txt_PlainText")
        self.txt_Key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Key.setGeometry(QtCore.QRect(120, 210, 521, 31))
        self.txt_Key.setObjectName("txt_Key")
        self.txt_CipherText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_CipherText.setGeometry(QtCore.QRect(120, 260, 521, 101))
        self.txt_CipherText.setObjectName("txt_CipherText")
        self.lbl_CaesarCipher = QtWidgets.QLabel(self.centralwidget)
        self.lbl_CaesarCipher.setGeometry(QtCore.QRect(220, 20, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_CaesarCipher.setFont(font)
        self.lbl_CaesarCipher.setObjectName("lbl_CaesarCipher")
        self.lbl_PlainText = QtWidgets.QLabel(self.centralwidget)
        self.lbl_PlainText.setGeometry(QtCore.QRect(16, 90, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_PlainText.setFont(font)
        self.lbl_PlainText.setObjectName("lbl_PlainText")
        self.lbl_Key = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Key.setGeometry(QtCore.QRect(20, 210, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_Key.setFont(font)
        self.lbl_Key.setObjectName("lbl_Key")
        self.lbl_CipherText = QtWidgets.QLabel(self.centralwidget)
        self.lbl_CipherText.setGeometry(QtCore.QRect(20, 260, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_CipherText.setFont(font)
        self.lbl_CipherText.setObjectName("lbl_CipherText")
        self.btn_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Encrypt.setGeometry(QtCore.QRect(170, 410, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_Encrypt.setFont(font)
        self.btn_Encrypt.setObjectName("btn_Encrypt")
        self.btn_Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Decrypt.setGeometry(QtCore.QRect(510, 410, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_Decrypt.setFont(font)
        self.btn_Decrypt.setObjectName("btn_Decrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_CaesarCipher.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.lbl_PlainText.setText(_translate("MainWindow", "Plain text:"))
        self.lbl_Key.setText(_translate("MainWindow", "Key:"))
        self.lbl_CipherText.setText(_translate("MainWindow", "CipherText:"))
        self.btn_Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_Decrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
